Avoid triggering context lifecycle errors from querytime
In commit 0039ce66c5, which disabled the querytime mechanism by default,
I wrote that it’s probably not necessary to make the flush_querytime()
call itself conditional. However, that call interacts badly with the
later commit fa4f0b15c3, caching the database in the application
context: apparently, by the time sometimes_flush_querytime() runs, the
application context is no longer alive, so we get:

> RuntimeError: Working outside of application context.
>
> This typically means that you attempted to use functionality that needed
> the current application. To solve this, set up an application context
> with app.app_context(). See the documentation for more information.

For now, work around this by using the private _connect() method to
ensure we open a fresh connection. In the longer term, it’s probably
time to completely rip out the querytime mechanism sooner or later.