Fix submitted_request_valid() for missing referrer
If a client does not send a Referer header, then flask.request.referrer
is None and we can’t call .startswith(…) on it, as mypy pointed out:

> app.py:186: error: Item "None" of "Optional[str]" has no attribute "startswith"

Fix this by falling back to an empty string in that case, which is fine
since the empty string can never start with the index URL (which
contains at least a slash), so this case is correctly identified as a
referrer mismatch.